# -*- coding: utf-8 -*-
"""image makes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SYy6MBWKq07cOWzkkIpKBswMtlF2eiZ
"""

!pip install -U "huggingface-hub<1.0,>=0.23.2"

import importlib.metadata as md

for p in ["transformers", "huggingface-hub", "diffusers", "gradio", "gradio-client", "tokenizers"]:
    try:
        print(p, "==", md.version(p))
    except:
        print(p, "NOT INSTALLED")

!git clone https://github.com/ToTheBeginning/PuLID.git /content/PuLID

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip uninstall -y transformers huggingface-hub diffusers gradio gradio-client tokenizers -q

!pip install -q \
  "huggingface-hub==0.24.7" \
  "transformers==4.44.2" \
  "tokenizers==0.19.1" \
  "diffusers==0.30.3" \
  "gradio==4.44.1" \
  "gradio-client==1.3.0"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip install -q insightface==0.7.3 onnxruntime

import insightface
import onnxruntime

print("insightface:", insightface.__version__)
print("onnxruntime:", onnxruntime.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip uninstall -y peft -q
!pip install -q "peft==0.13.2"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip uninstall -y transformers tokenizers peft -q

!pip install --no-cache-dir -q \
    "transformers==4.44.2" \
    "tokenizers==0.19.1" \
    "peft==0.13.2" \
    "requests>=2.31.0"

import shutil
import os
import glob

paths = glob.glob("/usr/local/lib/python3.12/dist-packages/transformers*")

print("Removing:")
for p in paths:
    print(p)
    if os.path.isdir(p):
        shutil.rmtree(p, ignore_errors=True)
    else:
        try:
            os.remove(p)
        except:
            pass

print("DONE")

import transformers
import tokenizers

print("transformers:", transformers.__version__)
print("tokenizers:", tokenizers.__version__)

import huggingface_hub
import diffusers
import peft
import insightface

print("hub:", huggingface_hub.__version__)
print("diffusers:", diffusers.__version__)
print("peft:", peft.__version__)
print("insightface:", insightface.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip install -q facexlib

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip install -q ftfy

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID
!pip install -q torchsde

import torch
print("CUDA:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", torch.cuda.get_device_properties(0).total_memory / 1024**3, "GB")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID

!pip uninstall -y gradio gradio-client

!pip install -q gradio==4.44.1 gradio-client==1.3.0

import gradio
import gradio_client

print("gradio:", gradio.__version__)
print("gradio-client:", gradio_client.__version__)

!pip uninstall -y gradio gradio_client
!pip install -q gradio==5.49.1 gradio_client==1.13.3

!python -c "import gradio, gradio_client, pydantic; print('gradio=',gradio.__version__); print('gradio_client=',gradio_client.__version__); print('pydantic=',pydantic.__version__)"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PuLID
!python app.py